support SHA-256 for v0.10.0 and above

diff --git a/bin/node-build b/bin/node-build
--- a/bin/node-build
+++ b/bin/node-build
@@ -150,37 +150,76 @@ make_package() {
 }
 
 compute_sha1() {
+  local output
   if type shasum &>/dev/null; then
-    local output="$(shasum)"
-    echo $output | awk '{print $1}'
+    output="$(shasum -a 1 -b)" || return 1
+    echo "${output% *}"
+  elif type openssl &>/dev/null; then
+    local openssl="$(command -v "$(brew --prefix openssl 2>/dev/null || true)"/bin/openssl openssl | head -1)"
+    output="$("$openssl" dgst -sha1 2>/dev/null)" || return 1
+    echo "${output##* }"
   elif type sha1sum &>/dev/null; then
-    local output="$(sha1sum)"
-    echo $output | awk '{print $1}'
+    output="$(sha1sum --quiet)" || return 1
+    echo "${output% *}"
+  else
+    return 1
+  fi
+}
+
+compute_sha2() {
+  local output
+  if type shasum &>/dev/null; then
+    output="$(shasum -a 256 -b)" || return 1
+    echo "${output% *}"
+  elif type openssl &>/dev/null; then
+    local openssl="$(command -v "$(brew --prefix openssl 2>/dev/null || true)"/bin/openssl openssl | head -1)"
+    output="$("$openssl" dgst -sha256 2>/dev/null)" || return 1
+    echo "${output##* }"
+  elif type sha256sum &>/dev/null; then
+    output="$(sha256sum --quiet)" || return 1
+    echo "${output% *}"
   else
     return 1
   fi
 }
 
 verify_checksum() {
-  # If there's no SHA1 support, return success
-  [ -n "$HAS_SHA1_SUPPORT" ] || return 0
-
   # If the specified filename doesn't exist, return success
   local filename="$1"
   [ -e "$filename" ] || return 0
 
   # If there's no expected checksum, return success
-  local expected_checksum="$2"
+  local expected_checksum=`echo "$2" | tr [A-Z] [a-z]`
   [ -n "$expected_checksum" ] || return 0
+  local expected_checksum_length="${#expected_checksum}"
+
+  # If the checksum length is 40 chars, assume SHA-1
+  if [ "$expected_checksum_length" -eq 40 ]; then
+
+    # If there's no SHA1 support, return success
+    [ -n "$HAS_SHA1_SUPPORT" ] || return 0
+    local checksum_command="compute_sha1"
+
+  # If the checksum length is 40 chars, assume SHA-256
+  elif [ "$expected_checksum_length" -eq 64 ]; then
+
+    # If there's no SHA2 support, return success
+    [ -n "$HAS_SHA2_SUPPORT" ] || return 0
+    local checksum_command="compute_sha2"
+
+  # Otherwise return failure
+  else
+    return 1
+  fi
 
   # If the computed checksum is empty, return failure
-  local computed_checksum="$(compute_sha1 < "$filename")"
+  local computed_checksum=`echo "$($checksum_command < "$filename")" | tr [A-Z] [a-z]`
   [ -n "$computed_checksum" ] || return 1
 
   if [ "$expected_checksum" != "$computed_checksum" ]; then
     { echo
       echo "checksum mismatch: ${filename} (file is corrupt)"
-      echo "expected '$expected_checksum', got '$computed_checksum'"
+      echo "expected $expected_checksum, got $computed_checksum"
       echo
     } >&4
     return 1
@@ -488,9 +527,16 @@ install_node() {
         v0.[1234567].*) binavail=0 ;;
         *) binavail=1 ;;
       esac
+      sha_algorithm=
+      # checksum is SHA256 in v0.10 and above and SHA1 in v0.9 and below
+      case "$VERSION" in
+        v0.[0-9].*) sha_algorithm= ;;
+        *) sha_algorithm=256 ;;
+      esac
+
       if [ $binavail -eq 1 ]; then
         t="$VERSION-$os-$arch"
-        sum=`curl -s http://nodejs.org/dist/$VERSION/SHASUMS.txt | grep node-${t}.tar.gz | awk '{print $1}'`
+        sum=`curl -s http://nodejs.org/dist/$VERSION/SHASUMS${sha_algorithm}.txt | grep node-${t}.tar.gz | awk '{print $1}'`
         url="http://nodejs.org/dist/$VERSION/node-${t}.tar.gz#${sum}"
         install_package "node-${t}" "$url" copy
       fi
@@ -561,6 +607,12 @@ if echo test | compute_sha1 >/dev/null; then
   HAS_SHA1_SUPPORT=1
 else
   unset HAS_SHA1_SUPPORT
+fi
+
+if echo test | compute_sha2 >/dev/null; then
+  HAS_SHA2_SUPPORT=1
+else
+  unset HAS_SHA2_SUPPORT
 fi
 
 SEED="$(date "+%Y%m%d%H%M%S").$$"
